apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: {{ .Values.global.database.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: {{ .Values.global.database.name }}
            - name: POSTGRES_USER
              value: {{ .Values.global.database.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.global.database.password }}
          ports:
            - containerPort: {{ .Values.global.database.port }}
