global:

  app:
    dockerImagePrefix: java-benchmarks
    imagePullPolicy: IfNotPresent
    replicaCount: 1
    port: 8080

  database:
    replicaCount: 1
    host: "jdbc:postgresql://postgres-service:5432/testdb"
    port: 5432
    name: testdb
    username: "user"
    password: "password"
