global:

  app:
    imagePullPolicy: Always
    replicaCount: 1
    port: 8080

  database:
    replicaCount: 1
    port: 5432
    name: testdb
    username: "user"
    password: "password"

  pgbouncer:
    host: "jdbc:postgresql://pgbouncer-service:6432/testdb"
    port: 6432