resources:
  requests:
    memory: 500Mi
    cpu: 200m
  limits:
    memory: 1Gi
    cpu: 500m

nodeSelector:
  kubernetes.io/hostname: client

service:
  type: NodePort
  port: 3000
  nodePort: 31993

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        jsonData:
          timeInterval: "2s"
