server:
  retention: 2h
  scrape_interval: 2s
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1
  nodeSelector:
    kubernetes.io/hostname: client

alertmanager:
  nodeSelector:
    kubernetes.io/hostname: client

pushgateway:
  nodeSelector:
    kubernetes.io/hostname: client
